# Generated by Django 4.0 on 2021-12-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.TextField(default='202112300958')),
                ('number', models.TextField(default='0,0,0,0,0,0,0')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'period+history',
            },
        ),
    ]
