# Generated by Django 4.0 on 2022-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='created',
        ),
        migrations.AddField(
            model_name='period',
            name='bip39',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='period',
            name='sha256',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='period',
            name='number',
            field=models.TextField(default='0,0,0,0,0'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
