# Generated by Django 4.0 on 2022-01-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0002_remove_period_created_period_bip39_period_sha256_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='period',
            table='period+history',
        ),
    ]
