# Generated by Django 4.0 on 2022-01-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0003_alter_period_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='period',
            table='period+history',
        ),
    ]
