# Generated by Django 4.0 on 2022-01-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Lottory',
        ),
    ]
