# Generated by Django 4.0 on 2022-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottory', '0002_rename_music_lottory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottory',
            name='period',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
